# Shepherd Gitlab CI script
shepherd:
  script:
    - killall ssh-agent
    - eval $(ssh-agent)
    - echo "${JENKINS_DEPLOYMENT_KEY}" > /tmp/jenkins_deployment_key
    - chmod 0600 /tmp/jenkins_deployment_key
    - ssh-add /tmp/jenkins_deployment_key
    - ssh-add -l
    - docker pull uofa/apache2-php7-dev:shepherd
    - docker pull mariadb
    - mkdir -p ~/.ssh && chmod 0700 ~/.ssh
    - ssh-keyscan -H gitlab.adelaide.edu.au > ~/.ssh/known_hosts
    - echo "Host *" > ~/.ssh/config && echo "    StrictHostKeyChecking no" >> ~/.ssh/config
    - docker run --rm -v $(pwd):/app -v $SSH_AUTH_SOCK:/ssh-auth.sock -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v ${HOME}:${HOME} --user $(id -u):$(id -g) --env SSH_AUTH_SOCK=/ssh-auth.sock composer install --ignore-platform-reqs
    - ./dsh start
    - sleep 10
    - ./dsh exec $(basename ${CI_JOB_NAME} | sed 's/[-_]//g')_web_1 root 'chmod -R 777 /web/app/sites/default'
    # This is one big long command line passed to the utility container.
    - ./dsh exec bash -c '
        export GITLAB_CI=true &&
        export SIMPLETEST_DB=\'mysql://user:password@db/drupal\' &&
        cd /code &&
        sudo phpdismod xdebug && robo build &&
        ./bin/phpunit --group ua --testdox -c ./app/core ./app/modules';
  after_script:
    - ./dsh exec $(basename ${CI_JOB_NAME} | sed 's/[-_]//g')_web_1 root 'rm -rf /web/app/sites/default'
    - ./dsh purge
  tags:
  except:
  - tags
