# Shepherd Gitlab CI script
shepherd:
  script:
    - eval `ssh-agent`
    - echo "${JENKINS_DEPLOYMENT_KEY}" > /tmp/jenkins_deployment_key
    - chmod 0600 /tmp/jenkins_deployment_key
    - ssh-add /tmp/jenkins_deployment_key
    - ssh-add -l
    - docker pull uofa/apache2-php7-dev:shepherd
    - docker pull mariadb
    - docker run --rm -v $(pwd):/app --volume $SSH_AUTH_SOCK:/ssh-auth.sock --volume /etc/passwd:/etc/passwd:ro --volume /etc/group:/etc/group:ro --user $(id -u):$(id -g) --env SSH_AUTH_SOCK=/ssh-auth.sock composer install --ignore-platform-reqs
    - ./dsh start
    - sleep 10
    - ./dsh exec $(basename ${CI_JOB_NAME} | sed 's/[-_]//g')_web_1 root 'chmod -R 777 /web/app/sites/default'
    # This is one big long command line passed to the utility container.
    - ./dsh exec bash -c '
        export GITLAB_CI=true &&
        export SIMPLETEST_DB=\'mysql://user:password@db/drupal\' &&
        cd /code &&
        mkdir -p ~/.ssh &&
        ssh-keyscan -H gitlab.adelaide.edu.au >> ~/.ssh/known_hosts &&
        sudo phpdismod xdebug && robo build &&
        ./bin/phpunit --group ua --testdox -c ./app/core ./app/modules';
  after_script:
    - ./dsh exec $(basename ${CI_JOB_NAME} | sed 's/[-_]//g')_web_1 root 'rm -rf /web/app/sites/default'
    - ./dsh purge
  tags:
  except:
  - tags
