version: '3'
services:
  web:
    image: uofa/apache2-php7-dev:foundation
    # This makes the container run on the same network stack as your
    # workstation. Meaning that you can interact on "localhost".
    ports:
      - 8000:80
    environment:
      SITE_TITLE: Shepherd
      SITE_MAIL: site@example.com
      SITE_ADMIN_EMAIL: admin@example.com
      SITE_ADMIN_USERNAME: admin
      SITE_ADMIN_PASSWORD: password
      DATABASE_HOST: db
      PUBLIC_DIR: /shared/public
      HASH_SALT: random-hash
      CONFIG_SYNC_DIRECTORY: /shared/private/random-hash/sync
      REDIS_ENABLED: 1
      REDIS_HOST: redis
      SHEPHERD_INSTALL_PROFILE: shepherd
      SHEPHERD_SECRET_PATH: /code/private
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: serverName=shepherd.172.17.0.1.nip.io
      VIRTUAL_HOST: ${PROJECT}.172.17.0.1.nip.io
    volumes:
      - .:/code
      - ./shared:/shared
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
    networks:
      - default

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: super-secret-password
    networks:
    - default

  mail:
    image: mailhog/mailhog
    networks:
    - default

  redis:
    image: redis:alpine
    networks:
    - default

networks:
  default:

