version: '3'
services:
  web:
    image: uofa/apache2-php7-dev:foundation
    # Chrome webdriver requires this - used for tests.
    privileged: true
    hostname: ${PROJECT}
    ports:
      - 8000:80
    environment:
      SITE_TITLE: Shepherd
      SITE_MAIL: site@example.com
      SITE_ADMIN_EMAIL: admin@example.com
      SITE_ADMIN_USERNAME: admin
      SITE_ADMIN_PASSWORD: password
      DATABASE_HOST: db
      PUBLIC_DIR: /shared/public
      PRIVATE_DIR: /shared/private
      TMP_DIR: /shared/tmp
      HASH_SALT: random-hash
      CONFIG_SYNC_DIRECTORY: /shared/private/random-hash/sync
      REDIS_ENABLED: 1
      REDIS_HOST: redis
      SHEPHERD_INSTALL_PROFILE: shepherd
      SHEPHERD_SECRET_PATH: /code/private
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: serverName=${PROJECT}.${DOMAIN}
      VIRTUAL_HOST: ${PROJECT}.${DOMAIN}
    volumes:
      - .:/code
      - ./shared:/shared
      - ${HOST_SSH_AUTH_SOCK_DIR}:/ssh
    networks:
      - default

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: super-secret-password
    networks:
    - default

  mail:
    image: mailhog/mailhog
    networks:
      - default
    ports:
      - 8025:80
    environment:
      - VIRTUAL_HOST=mail.${PROJECT}.${DOMAIN}

  redis:
    image: redis:alpine
    networks:
      - default

networks:
  default:

