#!/bin/bash

# `set +e` is used to continue on errors throughout this script.
set -euo pipefail
IFS=$'\n\t'

if [ -f /.dockerenv ]; then
  error "Inception error - you can't run $0 within a docker container."
  exit
fi

openshift_start() {
  crc setup
  crc start
  echo "Wait a few seconds and then start shepherd with ./dsh"
}

openshift_stop() {
  ./dsh stop
  crc stop
}

openshift_purge() {
  ./dsh purge
  crc delete
}

COMMAND=${1:-default}

case ${COMMAND} in
  sta*)
    openshift_start
    ;;
  sto*)
    openshift_stop
    ;;
  p*)
    openshift_purge
    ;;
  *)
    printf "Unknown command specified. Try:\n$0 [start|stop|purge].\n"
    exit 0
    ;;
esac
