#!/bin/bash

# `set +e` is used to continue on errors throughout this script.
set -euo pipefail
IFS=$'\n\t'

if [ -f /.dockerenv ]; then
  error "Inception error - you can't run $0 within a docker container."
  exit
fi

openshift_start() {
  docker run -d --name microshift --privileged -v microshift-data:/var/lib -p 6443:6443 quay.io/microshift/microshift-aio:latest
  # Perform some slight shenanigans to get stuff working in microshift.
  docker exec -it microshift oc adm new-project openshift-config
  docker exec -it microshift yum -y install git podman python39 python39-pyyaml
  docker exec -it microshift bash -c "cat /var/lib/microshift/resources/kubelet/config/config.yaml | python3 -c 'import sys, yaml, json
json.dump(yaml.load(stream=sys.stdin, Loader=yaml.Loader), sys.stdout, indent=4)' > /var/lib/kubelet/config.json
  "
  docker exec -it microshift bash -c "cat <<EOF | oc apply -n openshift-config -f -
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  additionalTrustedCA:
    name: \"openshift-service-ca.crt\"
EOF"

  echo "Wait a few seconds and then start shepherd with ./dsh"
}

openshift_stop() {
  ./dsh stop
  docker stop microshift
}

openshift_purge() {
  ./dsh purge
  docker stop microshift
  docker rm microshift
}

COMMAND=${1:-default}

case ${COMMAND} in
  sta*)
    openshift_start
    ;;
  sto*)
    openshift_stop
    ;;
  p*)
    openshift_purge
    ;;
  *)
    printf "Unknown command specified. Try:\n$0 [start|stop|purge].\n"
    exit 0
    ;;
esac
