#!/bin/bash

# `set +e` is used to continue on errors throughout this script.
set -euo pipefail
IFS=$'\n\t'

if [ -f /.dockerenv ]; then
  error "Inception error - you can't run $0 within a docker container."
  exit
fi

openshift_start() {
  crc setup
  echo "Starting CodeReady Containers."
  echo "Expect 20+ minutes from fresh setup, 8+ minutes subsequent. Coffee?"
  crc start -n 1.1.1.1
  echo "Logging in."
  oc login -u developer https://api.crc.testing:6443
  echo "Waiting a few seconds."
  sleep 5
  ./dsh
}

openshift_stop() {
  ./dsh stop
  crc stop
}

openshift_purge() {
  ./dsh purge
  crc delete
  echo "Cleaning up serviceaccount temp files."
  for i in {0..4} ; do
    SA=$(printf 'shepherd-prd-provisioner-00%02d' "$i")
    if [ -f ".${SA}.token" ]; then
      rm ".${SA}.token"
    fi
  done
}

COMMAND=${1:-default}

case ${COMMAND} in
  star*)
    openshift_start
    ;;
  stat*)
    crc status
    ;;
  sto*)
    openshift_stop
    ;;
  p*)
    openshift_purge
    ;;
  *)
    printf "Unknown command specified. Try:\n$0 [start|status|stop|purge].\n"
    exit 0
    ;;
esac
