apiVersion: v1
data:
  redis-config: |
    maxmemory 240Mi
    maxmemory-policy allkeys-lru
    save ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: redis-config
  selfLink: /api/v1/namespaces/myproject/configmaps/redis-config
