apiVersion: v1
kind: Template
labels:
  template: shepherd
message: |-
  This template will create a shepherd deployment
metadata:
  annotations:
    iconClass: icon-php
    openshift.io/display-name: Drupal + MySQL
    description: Provide a template that deploys an instance of the shepherd distribution.
    tags: php
    template.openshift.io/documentation-url: https://gitlab.adelaide.edu.au/web-team/shepherd
    template.openshift.io/long-description: This template defines resources needed
      to run the Shepherd site manager.
    template.openshift.io/provider-display-name: University of Adelaide
    template.openshift.io/support-url: https://www.adelaide.edu.au
  name: shepherd
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[{"name":"${DATABASE_SERVICE_NAME}",
        "kind":"Service"}]'
    name: ${NAME}-svc
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}-route
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}-svc
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}-imagestream
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: ${NAME}-bc
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-imagestream:latest
    postCommit: {}
    source:
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
      secrets:
      - destinationDir: .
        secret:
          name: ${OPENSHIFT_KEY}
      sourceSecret:
        name: ${OPENSHIFT_KEY}
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: uofa/s2i-shepherd-drupal
        pullSecret:
          name: ${OPENSHIFT_KEY}
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_TRIGGER_SECRET}
      type: Generic
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}-private
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}-public
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: ${NAME}-dc
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.shepherd.image.entrypoint: '["/usr/local/s2i/run"]'
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: DATABASE_HOST
            value: ${DATABASE_SERVICE_NAME}
          - name: DATABASE_NAME
            value: ${DATABASE_NAME}
          - name: DATABASE_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_USER
            value: ${DATABASE_USER}
          - name: PRIVATE_DIR
            value: /code/private
          - name: PUBLIC_DIR
            value: /code/web/sites/default/files
          image: ' '
          name: ${NAME}
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          volumeMounts:
          - mountPath: /code/web/sites/default/files
            name: ${NAME}-public
          - mountPath: /code/private
            name: ${NAME}-private
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${NAME}-public
          persistentVolumeClaim:
            claimName: ${NAME}-public
        - name: ${NAME}-private
          persistentVolumeClaim:
            claimName: ${NAME}-private
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}-imagestream:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the database server
    name: ${DATABASE_SERVICE_NAME}
  spec:
    ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    selector:
      name: ${DATABASE_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the database
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
        name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: ${DATABASE_NAME}
          - name: MYSQL_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: MYSQL_USER
            value: ${DATABASE_USER}
          image: ''
          name: mysql
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD='${DATABASE_PASSWORD}' mysql -h 127.0.0.1 -u ${DATABASE_USER}
                -D ${DATABASE_NAME} -e 'SELECT 1'
          resources:
            limits:
              memory: ${MEMORY_MYSQL_LIMIT}
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: ${DATABASE_SERVICE_NAME}-volume-1
        volumes:
        - emptyDir: {}
          name: ${DATABASE_SERVICE_NAME}-volume-1
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mariadb:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: shepherd-web
- description: Enter the name of the pre-created passwordless secret that allows you to checkout from gitlab.
  displayName: ssh key
  name: OPENSHIFT_KEY
  required: true
  value: 'build-key'
- displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: shepherd-mysql
- description: Maximum amount of memory the Drupal container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 128Mi
- description: Maximum amount of memory the MySQL container can use.
  displayName: Memory Limit (MySQL)
  name: MEMORY_MYSQL_LIMIT
  required: true
  value: 256Mi
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: ssh://git@gitlab.adelaide.edu.au/web-team/shepherd.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: develop
- description: The exposed hostname that will route to the Drupal service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- displayName: Database Name
  name: DATABASE_NAME
  required: true
  value: default
- displayName: Database User
  name: DATABASE_USER
  required: true
  value: drupal
- displayName: Database Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_PASSWORD
