apiVersion: v1
kind: Template
objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    labels:
      app: shepherd
      template: shepherd-cronjob-cleaner
      name: shepherd-cronjob-cleaner
    name: shepherd-cronjob-cleaner
  spec:
    concurrencyPolicy: Forbid
    schedule: '5 * * * *'
    suspend: false
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    jobTemplate:
      spec:
        template:
          spec:
            activeDeadlineSeconds: 600
            serviceAccountName: scheduled-jobs-cleanup
            containers:
            - image: pingers/openshift-scheduledjobs-cleanup:latest
              imagePullPolicy: IfNotPresent
              name: scheduled-jobs-cleanup
              resources:
                limits:
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            terminationGracePeriodSeconds: 30
