apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: shepherd-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: minio
  template:
    metadata:
      labels:
        deployment: minio
    spec:
      containers:
        - name: minio
          image: "docker.io/minio/minio:latest"
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "mkdir -p /data/local && minio server /data"
          env:
            - name: MINIO_ACCESS_KEY
              value: shepherd
            - name: MINIO_SECRET_KEY
              value: password123
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-data
      volumes:
        - name: minio-data
          emptyDir: {}
