apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: shepherd-dev
spec:
  ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    deployment: minio
  type: ClusterIP
