# Configuration schema for shp_backup module

shp_backup.settings:
  type: mapping
  label: 'Shepherd backup settings'
  mapping:
    backup_service:
      type: mapping
      label: 'Backup Service'
      mapping:
        root_dir:
          type: string
          label: 'Backup root directory'
        backup_title:
          type: string
          label: 'Backup title'
        backup_command:
          type: string
          label: 'Backup command'
        restore_command:
          type: string
          label: 'Restore command'
