<?php

/**
 * @file
 * Contains shp_database_provisioner.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\shp_database_provisioner\Service\Provisioner;


/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function shp_database_provisioner_node_insert(EntityInterface $entity) {
  \Drupal::service('shp_database_provisioner.provisioner')->create($entity);
}

/**
 * Implements hook_shp_env_vars().
 */
function shp_database_provisioner_shp_env_vars(EntityInterface $entity) {
  $config = \Drupal::config('shp_database_provisioner.settings');
  return [
    Provisioner::ENV_MYSQL_HOSTNAME => $config->get('host'),
    Provisioner::ENV_MYSQL_PORT => $config->get('port'),
    Provisioner::ENV_MYSQL_DATABASE => 'env_' . $entity->id(),
    Provisioner::ENV_MYSQL_USERNAME => 'user_' . $entity->id(),
    // The following path is based on convention set in:
    // OpenShiftOrchestrationProvider::setupVolumes()
    // The 'default' deployment config secret is mounted at /etc/secret.
    'DATABASE_PASSWORD_FILE' => '/etc/secret/DATABASE_PASSWORD',
  ];
}
