apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shepherd-operator
rules:
  - apiGroups:
      - extension.shepherd
    resources:
      - backups
      - backupscheduleds
      - restores
      - syncs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extension.shepherd
    resources:
      - backups/status
      - backupscheduleds/status
      - restores/status
      - syncs/status
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - extension.shepherd
    resources:
      - backups/finalizers
      - backupscheduleds/finalizers
      - restores/finalizers
      - syncs/finalizers
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
