apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shepherd-operator
  namespace: shepherd-prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shepherd-operator
subjects:
- kind: ServiceAccount
  name: shepherd-sa
  namespace: shepherd-prd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shepherd-operator
  namespace: shepherd-uat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shepherd-operator
subjects:
- kind: ServiceAccount
  name: shepherd-sa
  namespace: shepherd-uat
