apiVersion: v1
data:
  standalone.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <server xmlns="urn:jboss:domain:8.0">
      <extensions>
        <extension module="org.infinispan.extension"/>
        <extension module="org.infinispan.server.endpoint"/>
        <extension module="org.jboss.as.connector"/>
        <extension module="org.jboss.as.deployment-scanner"/>
        <extension module="org.jboss.as.jdr"/>
        <extension module="org.jboss.as.jmx"/>
        <extension module="org.jboss.as.logging"/>
        <extension module="org.jboss.as.naming"/>
        <extension module="org.jboss.as.remoting"/>
        <extension module="org.jboss.as.security"/>
        <extension module="org.jboss.as.transactions"/>
        <extension module="org.jgroups.extension"/>
        <extension module="org.wildfly.extension.io"/>
      </extensions>
      <management>
        <security-realms>
          <security-realm name="ManagementRealm">
            <authentication>
              <local default-user="$local"/>
              <properties path="mgmt-users.properties" relative-to="jboss.server.config.dir"/>
            </authentication>
            <authorization map-groups-to-roles="false">
              <properties path="mgmt-groups.properties" relative-to="jboss.server.config.dir"/>
            </authorization>
          </security-realm>
          <security-realm name="ApplicationRealm">
            <authentication>
              <local default-user="$local" allowed-users="*"/>
              <properties path="application-users.properties" relative-to="jboss.server.config.dir"/>
            </authentication>
            <authorization>
              <properties path="application-roles.properties" relative-to="jboss.server.config.dir"/>
            </authorization>
          </security-realm>
          <security-realm name="jdg-openshift">
            <authentication>
              <jaas name="jdg-openshift"/>
            </authentication>
          </security-realm>
        </security-realms>
        <audit-log>
          <formatters>
            <json-formatter name="json-formatter"/>
          </formatters>
          <handlers>
            <file-handler name="file" formatter="json-formatter" relative-to="jboss.server.data.dir" path="audit-log.log"/>
          </handlers>
          <logger log-boot="true" log-read-only="false" enabled="false">
            <handlers>
              <handler name="file"/>
            </handlers>
          </logger>
        </audit-log>
        <management-interfaces>
          <http-interface console-enabled="false">
            <http-upgrade enabled="true"/>
            <socket-binding http="management-http"/>
          </http-interface>
        </management-interfaces>
        <access-control provider="simple">
          <role-mapping>
            <role name="SuperUser">
              <include>
                <user name="$local"/>
              </include>
            </role>
          </role-mapping>
        </access-control>
      </management>
      <profile>
        <subsystem xmlns="urn:jboss:domain:logging:6.0">
          <console-handler name="CONSOLE">
            <formatter>
              <named-formatter name="COLOR-PATTERN"/>
            </formatter>
          </console-handler>
          <periodic-rotating-file-handler name="FILE" autoflush="true">
            <formatter>
              <named-formatter name="PATTERN"/>
            </formatter>
            <file relative-to="jboss.server.log.dir" path="server.log"/>
            <suffix value=".yyyy-MM-dd"/>
            <append value="true"/>
          </periodic-rotating-file-handler>
          <size-rotating-file-handler name="HR-ACCESS-FILE" autoflush="true">
            <formatter>
              <named-formatter name="ACCESS-LOG"/>
            </formatter>
            <file relative-to="jboss.server.log.dir" path="hotrod-access.log"/>
            <append value="true"/>
            <rotate-size value="10M"/>
            <max-backup-index value="10"/>
          </size-rotating-file-handler>
          <size-rotating-file-handler name="REST-ACCESS-FILE" autoflush="true">
            <formatter>
              <named-formatter name="ACCESS-LOG"/>
            </formatter>
            <file relative-to="jboss.server.log.dir" path="rest-access.log"/>
            <append value="true"/>
            <rotate-size value="10M"/>
            <max-backup-index value="10"/>
          </size-rotating-file-handler>
            <logger category="com.arjuna">
                <level name="WARN"/>
            </logger>
            <logger category="org.jboss.as.config">
                <level name="DEBUG"/>
            </logger>
            <logger category="sun.rmi">
                <level name="WARN"/>
            </logger>
          <logger category="org.infinispan.HOTROD_ACCESS_LOG" use-parent-handlers="false">
            <!-- Set to TRACE to enable access logging for hot rod or use DMR -->
            <level name="INFO"/>
            <handlers>
              <handler name="HR-ACCESS-FILE"/>
            </handlers>
          </logger>
          <root-logger>
            <level name="INFO"/>
            <handlers>
              <handler name="CONSOLE"/>
              <handler name="FILE"/>
            </handlers>
          </root-logger>
          <formatter name="OPENSHIFT">
            <json-formatter>
                <exception-output-type value="formatted"/>
                <key-overrides timestamp="@timestamp"/>
                <meta-data>
                    <property name="@version" value="1"/>
                </meta-data>
            </json-formatter>
          </formatter>
          <formatter name="PATTERN">
            <pattern-formatter pattern="%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"/>
          </formatter>
          <formatter name="COLOR-PATTERN">
            <pattern-formatter pattern="%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n"/>
          </formatter>
          <formatter name="ACCESS-LOG">
            <pattern-formatter pattern="%X{address} %X{user} [%d{dd/MMM/yyyy:HH:mm:ss z}] &quot;%X{method} %m %X{protocol}&quot; %X{status} %X{requestSize} %X{responseSize} %X{duration}%n"/>
          </formatter>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:deployment-scanner:2.0">
          <deployment-scanner path="deployments" relative-to="jboss.server.base.dir" scan-interval="5000" runtime-failure-causes-rollback="${jboss.deployment.scanner.rollback.on.failure:false}"/>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:datasources:5.0">
          <datasources>
            <datasource jta="true" jndi-name="java:jboss/datasources/ExampleDS" pool-name="ExampleDS" enabled="true" use-java-context="true">
              <connection-url>jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE</connection-url>
              <driver>h2</driver>
              <security>
                <user-name>sa</user-name>
                <password>sa</password>
              </security>
            </datasource>
            <drivers>
              <driver name="h2" module="com.h2database.h2">
                <xa-datasource-class>org.h2.jdbcx.JdbcDataSource</xa-datasource-class>
              </driver>
              <driver name="mysql" module="com.mysql">
                <xa-datasource-class>com.mysql.jdbc.jdbc2.optional.MysqlXADataSource</xa-datasource-class>
              </driver>
              <driver name="postgresql" module="org.postgresql">
                <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
              </driver>
            </drivers>
          </datasources>
        </subsystem>
        <subsystem xmlns="urn:infinispan:server:endpoint:9.4">
          <memcached-connector name="memcached_shepherd" cache-container="clustered" cache="memcached_shepherd" socket-binding="memcached_shepherd"/>
        </subsystem>
        <subsystem xmlns="urn:infinispan:server:core:9.4" default-cache-container="clustered">
          <cache-container statistics="true" name="clustered" default-cache="mycache">
            <transport channel="cluster"/>
            <global-state>
              <overlay-configuration-storage/>
            </global-state>
            <replicated-cache statistics="true" name="memcached_shepherd" mode="SYNC" start="EAGER">
              <memory>
                <object/>
              </memory>
            </replicated-cache>
            <distributed-cache statistics="true" name="mycache" mode="SYNC" start="EAGER">
              <memory>
                <object/>
              </memory>
            </distributed-cache>
            <distributed-cache statistics="true" name="default_memcached" mode="SYNC">
              <memory>
                <object/>
              </memory>
            </distributed-cache>
          </cache-container>
        </subsystem>
        <subsystem xmlns="urn:infinispan:server:jgroups:9.4">
          <channels default="cluster">
            <channel name="cluster" stack="tcp"/>
          </channels>
          <stacks>
            <stack name="udp">
              <transport type="UDP" socket-binding="jgroups-udp"/>
              <protocol type="openshift.DNS_PING" socket-binding="jgroups-mping"/>
              <protocol type="MERGE3"/>
              <protocol type="FD_SOCK" socket-binding="jgroups-udp-fd"/>
              <protocol type="FD_ALL"/>
              <protocol type="VERIFY_SUSPECT"/>
              <protocol type="pbcast.NAKACK2"/>
              <protocol type="UNICAST3"/>
              <protocol type="pbcast.STABLE"/>
              <protocol type="AUTH">
                <property name="auth_class">org.jgroups.auth.MD5Token</property>
                <property name="token_hash">SHA</property>
                <property name="auth_value">hK7JWWXv</property>
              </protocol>
              <protocol type="pbcast.GMS"/>
              <protocol type="UFC_NB"/>
              <protocol type="MFC_NB"/>
              <protocol type="FRAG3"/>
            </stack>
            <stack name="tcp">
              <transport type="TCP" socket-binding="jgroups-tcp"/>
              <protocol type="openshift.DNS_PING" socket-binding="jgroups-mping"/>
              <protocol type="MERGE3"/>
              <protocol type="FD_SOCK" socket-binding="jgroups-tcp-fd"/>
              <protocol type="FD_ALL"/>
              <protocol type="VERIFY_SUSPECT"/>
              <protocol type="pbcast.NAKACK2">
                <property name="use_mcast_xmit">false</property>
              </protocol>
              <protocol type="UNICAST3"/>
              <protocol type="pbcast.STABLE"/>
              <protocol type="AUTH">
                <property name="auth_class">org.jgroups.auth.MD5Token</property>
                <property name="token_hash">SHA</property>
                <property name="auth_value">hK7JWWXv</property>
              </protocol>
              <protocol type="pbcast.GMS"/>
              <protocol type="MFC_NB"/>
              <protocol type="FRAG3"/>
            </stack>
          </stacks>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:io:3.0">
          <worker name="default" io-threads="2" task-max-threads="2"/>
          <buffer-pool name="default"/>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:jca:5.0">
          <archive-validation enabled="true" fail-on-error="true" fail-on-warn="false"/>
          <bean-validation enabled="true"/>
          <default-workmanager>
            <short-running-threads>
              <core-threads count="50"/>
              <queue-length count="50"/>
              <max-threads count="50"/>
              <keepalive-time time="10" unit="seconds"/>
            </short-running-threads>
            <long-running-threads>
              <core-threads count="50"/>
              <queue-length count="50"/>
              <max-threads count="50"/>
              <keepalive-time time="10" unit="seconds"/>
            </long-running-threads>
          </default-workmanager>
          <cached-connection-manager/>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:jdr:1.0"/>
        <subsystem xmlns="urn:jboss:domain:jmx:1.3">
          <expose-resolved-model/>
          <expose-expression-model/>
          <remoting-connector/>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:naming:2.0">
          <remote-naming/>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:remoting:4.0"/>
        <subsystem xmlns="urn:jboss:domain:security:2.0">
          <security-domains>
            <security-domain name="other" cache-type="default">
              <authentication>
                <login-module code="Remoting" flag="optional">
                  <module-option name="password-stacking" value="useFirstPass"/>
                </login-module>
                <login-module code="RealmDirect" flag="required">
                  <module-option name="password-stacking" value="useFirstPass"/>
                </login-module>
              </authentication>
            </security-domain>
            <security-domain name="jboss-web-policy" cache-type="default">
              <authorization>
                <policy-module code="Delegating" flag="required"/>
              </authorization>
            </security-domain>
            <security-domain name="jaspitest" cache-type="default">
              <authentication-jaspi>
                <login-module-stack name="dummy">
                  <login-module code="Dummy" flag="optional"/>
                </login-module-stack>
                <auth-module code="Dummy"/>
              </authentication-jaspi>
            </security-domain>
            <security-domain name="jdg-openshift" cache-type="default">
              <authentication>
                <login-module code="RealmUsersRoles" flag="required">
                  <module-option name="usersProperties" value="${jboss.server.config.dir}/application-users.properties"/>
                  <module-option name="rolesProperties" value="${jboss.server.config.dir}/application-roles.properties"/>
                  <module-option name="realm" value="ApplicationRealm"/>
                </login-module>
              </authentication>
            </security-domain>
          </security-domains>
        </subsystem>
        <subsystem xmlns="urn:jboss:domain:transactions:5.0">
          <core-environment node-identifier="${jboss.node.name}">
            <process-id>
              <uuid/>
            </process-id>
          </core-environment>
          <recovery-environment socket-binding="txn-recovery-environment" status-socket-binding="txn-status-manager" recovery-listener="true"/>
          <coordinator-environment default-timeout="300"/>
        </subsystem>
      </profile>
      <interfaces>
        <interface name="management">
          <inet-address value="${jboss.bind.address.management:127.0.0.1}"/>
        </interface>
        <interface name="public">
          <inet-address value="${jboss.bind.address:127.0.0.1}"/>
        </interface>
      </interfaces>
      <socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
        <socket-binding name="management-http" interface="management" port="${jboss.management.http.port:9990}"/>
        <socket-binding name="management-https" interface="management" port="${jboss.management.https.port:9993}"/>
        <socket-binding name="jgroups-mping" port="0" multicast-address="${jboss.default.multicast.address:234.99.54.14}" multicast-port="45700"/>
        <socket-binding name="jgroups-tcp" port="7600"/>
        <socket-binding name="jgroups-tcp-fd" port="57600"/>
        <socket-binding name="jgroups-udp" port="55200" multicast-address="${jboss.default.multicast.address:234.99.54.14}" multicast-port="45688"/>
        <socket-binding name="jgroups-udp-fd" port="54200"/>
        <socket-binding name="memcached_shepherd" port="11211"/>
        <socket-binding name="txn-recovery-environment" port="4712"/>
        <socket-binding name="txn-status-manager" port="4713"/>
      </socket-binding-group>
    </server>
kind: ConfigMap
metadata:
  namespace: shepherd-dev-datagrid
  name: datagrid-config
