<?php

/**
 * @file
 * Contains ua_sm_drush_aliases.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\NodeType;


/**
 * Implements hook_entity_extra_field_info().
 */
function ua_sm_drush_aliases_entity_extra_field_info() {
  $extra = [];

  $node_type = NodeType::load('ua_sm_site');
  $extra['node'][$node_type->Id()]['display']['field_drush_aliases'] = [
    'label' => t('Drush aliases'),
    'description' => t('Download the Drush aliases for this site.'),
    'weight' => 100,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function ua_sm_drush_aliases_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode, $langcode) {
  if ($display->getComponent('field_drush_aliases')) {
    $url = Url::fromRoute('ua_sm_drush_aliases.drush_aliases', ['nid' => $entity->id()]);
    $markup = t('<a href="@link">Download Drush aliases</a>', [
      '@link' => $url->toString(),
    ]);
    $build['field_drush_aliases'] = [
      '#type' => 'markup',
      '#markup' => $markup,
    ];
  }
}
