<?php

/**
 * @file
 * Contains shp_custom.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\group\Entity\GroupContent;
use Drupal\node\Entity\Node;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function shp_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shp_custom module.
    case 'help.page.shp_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides functionality specific to the Shepherd.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function shp_custom_theme($existing, $type, $theme, $path) {
  return [
    'site_environment_status' => [
      'variables' => [
        'running' => NULL,
        'building' => NULL,
        'failed' => NULL,
        'environment' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_toolbar().
 */
function shp_custom_toolbar() {
  // Load the menu tree for shepherd.
  $menu_tree = \Drupal::service('toolbar.menu_tree');
  $parameters = new MenuTreeParameters();
  $parameters->setMinDepth(2)->setMaxDepth(2)->onlyEnabledLinks();
  $tree = $menu_tree->load('shepherd', $parameters);
  $links = $menu_tree->build($tree);

  // Declare our custom tab and tray.
  $items['shepherd'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Shepherd'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => [
        'title' => t('Shepherd menu'),
        'class' => ['toolbar-icon', 'toolbar-icon-system-admin-structure'],
        // A data attribute that indicates to the client to defer loading of
        // the admin menu subtrees until this tab is activated. Admin menu
        // subtrees will not render to the DOM if this attribute is removed.
        // The value of the attribute is intentionally left blank. Only the
        // presence of the attribute is necessary.
        'data-drupal-subtrees' => '',
      ],
    ],
    'tray' => [
      '#heading' => t('Shepherd menu'),
      '#attached' => '',
      'shepherd' => $links,
    ],
    '#weight' => -20,
  ];

  return $items;
}

/**
 * Generate a list of distributions for a select list.
 *
 * @return array
 *   The choices formatted as id => label.
 */
function shp_custom_distributions() {
  $ids = \Drupal::entityQuery('node')
    ->condition('type', 'shp_distribution')
    ->sort('title', 'ASC')
    ->execute();

  $entities = Node::loadMultiple($ids);

  $choices = [];
  foreach ($entities as $entity) {
    $choices[$entity->id()] = $entity->getTitle();
  }

  return $choices;
}

/**
 * Invalidate site entity caches because environments for sites have changed.
 *
 * @param \Drupal\Core\Entity\EntityInterface $environment
 *   The environment entity whose site needs cache invalidate.
 */
function shp_custom_invalidate_site_cache(EntityInterface $environment) {
  $site_nid = $environment->field_shp_site->target_id;
  if ($site_nid) {
    \Drupal::service('cache_tags.invalidator')->invalidateTags(['node:' . $site_nid]);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * Triggers jenkins jobs when an instance's status is changed.
 */
function shp_custom_node_update(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'shp_environment':
      shp_custom_invalidate_site_cache($entity);
      // @todo Shepherd: Add new environment to reverse proxy.
      // @todo Shepherd: Published environments should trigger re-deploy.
      // @todo Shepherd: Move state transitioning to environment?
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Triggers jenkins when site instances are deleted.
 *
 * @todo Shepherd: Don't do this at all and archive sites and environments.
 * @todo Shepherd: Move the decommissioning to environment update hook.
 */
function shp_custom_node_delete(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'shp_environment':
      shp_custom_invalidate_site_cache($entity);
      break;
  }
}

/**
 * Implements hook_node_access().
 *
 * Prevent production environments from being deleted.
 */
function shp_custom_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity->bundle() == 'shp_environment') {
    if ($operation == 'delete') {
      if ($entity->field_shp_machine_name->value === 'prd') {
        return AccessResult::forbidden();
      }
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_type_insert().
 *
 * @todo Shepherd: Modify this to be useful in some way. When environment ready?
 */
function shp_custom_comment_insert(EntityInterface $entity) {
  // Send an email notification to the user who created a site instance.
  $commented_entity = $entity->getCommentedEntity();

  if ($commented_entity->getType() === "shp_site") {
    $author = $commented_entity->getRevisionAuthor();
    $author_email = $author->getEmail();

    $mail_message = [
      'author_name' => $author->getAccountName(),
      'message' => $entity->comment_body->value,
      'subject' => $entity->getSubject(),
    ];
    $langcode = $author->getPreferredLangCode();

    $result = \Drupal::service('plugin.manager.mail')->mail('shp_custom', 'shp_site', $author_email, $langcode, $mail_message);

    if ($result['result'] !== TRUE) {
      drupal_set_message(t('There was an issue sending an email notification to %email with message %msg', ['%email' => $author_email, '%msg' => $entity->comment_body->value]), 'error');
      return;
    }

    drupal_set_message(t('An email notification has been sent to %user', ['%user' => $author->getAccountName()]));
  }

}

/**
 * Implements hook_mail().
 */
function shp_custom_mail($key, &$message, $params) {
  // Set the content of the email message, escape any html prior to send.
  switch ($key) {
    case 'shp_site':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Site Instance : @subject', ['subject' => $params['subject']]);
      $message['body'][] = t('Hello @name,', ['name' => $params['author_name']]);
      $message['body'][] = Html::escape($params['message']);
  }
}

/**
 * Implements hook_cron().
 */
function shp_custom_cron() {
  // Only run backups at 3am.
  if (date('G', time()) == 3) {
    shp_custom_backup_environments();
  }
}

/**
 * Back up all environments.
 */
function shp_custom_backup_environments() {
  // @todo Shepherd: Perform backups on orchestration provider.
}
