shp_orchestration.openshift.*:
  type: config_entity
  label: 'OpenShift orchestration configuration'
  mapping:
    id:
      type: string
      label: 'Config entity id'
    endpoint:
      label: 'Endpoint'
      type: string
    token:
      label: 'Token'
      type: string
    uuid:
      type: string
      label: 'UUID'
    namespace:
      type: string
      label: 'Namespace'
    verify_tls:
      type: boolean
      label: 'Verify TLS'
    uid:
      type: string
      label: 'User ID'
    gid:
      type: string
      label: 'Group ID'
