apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shepherd-operator-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shepherd-operator-proxy
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: shepherd-operator
