# permissions for end users to edit backups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shepherd-operator-backup-editor
rules:
- apiGroups:
  - extension.shepherd
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - backups/status
  verbs:
  - get
