# permissions for end users to view backupscheduleds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shepherd-operator-backupscheduled-viewer
rules:
- apiGroups:
  - extension.shepherd
  resources:
  - backupscheduleds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - backupscheduleds/status
  verbs:
  - get
