# permissions for end users to edit syncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shepherd-operator-sync-editor
rules:
- apiGroups:
  - extension.shepherd
  resources:
  - syncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - syncs/status
  verbs:
  - get
