---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: shepherd-operator-manager
rules:
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extension.shepherd
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - backups/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extension.shepherd
  resources:
  - backupscheduleds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - backupscheduleds/finalizers
  verbs:
  - update
- apiGroups:
  - extension.shepherd
  resources:
  - backupscheduleds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extension.shepherd
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - restores/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extension.shepherd
  resources:
  - syncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.shepherd
  resources:
  - syncs/finalizers
  verbs:
  - update
- apiGroups:
  - extension.shepherd
  resources:
  - syncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - v1
  resources:
  - pods/log
  verbs:
  - get
