<?php

/**
 * @file
 * Module file for UA links block.
 */

/**
 * Implements hook_entity_prepare_view().
 */
function ua_links_block_entity_prepare_view($entity_type_id, array $entities, array $displays, $view_mode) {
  if ($entity_type_id == 'block_content') {
    foreach ($entities as $entity) {
      if ($entity->bundle() == 'links') {
        foreach ($displays[$entity->bundle()]->getComponents() as $name => $options) {
          if ($name == 'field_links') {
            foreach ($entity->get($name) as $item) {
              $item->_attributes += array('class' => array('quick-links__menu-item__link'));
            }
          }
        }
      }
    }
  }
}
