kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  namespace: shepherd-operator
stringData:
  # Create new Github Personal Access Token with read:packages scope at https://github.com/settings/tokens/new.
  # <AUTH> is created by running: echo -n <your-github-username>:<TOKEN> | base64
  .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"<AUTH>"}}}'
